//! Write and update `~/.config/bunny/config.yaml` for a smoother dev experience.

use anyhow::{Context, Result, bail};
use bunny_core::config::BunnyConfig;
use bunny_discord::db::hash_token;
use serde::Deserialize;
use std::path::{Path, PathBuf};

#[derive(Deserialize)]
struct BridgeDevFile {
    discord: Option<BridgeDevDiscord>,
    bunny: BridgeDevBunny,
}

#[derive(Deserialize)]
struct BridgeDevDiscord {
    application_id: Option<u64>,
    guild_id: Option<u64>,
}

#[derive(Deserialize)]
struct BridgeDevBunny {
    bridge_token: String,
}

pub fn config_dir() -> PathBuf {
    let home = std::env::var("HOME").unwrap_or_else(|_| ".".into());
    PathBuf::from(home).join(".config/bunny")
}

pub fn config_path() -> PathBuf {
    config_dir().join("config.yaml")
}

/// Create `config.yaml` with sensible defaults if it does not exist.
pub fn ensure_user_config() -> Result<Option<PathBuf>> {
    let path = config_path();
    if path.is_file() {
        return Ok(None);
    }
    std::fs::create_dir_all(path.parent().unwrap())?;
    let mut cfg = BunnyConfig::default();
    if Path::new("/.dockerenv").exists() {
        cfg.server.bind_host = "0.0.0.0".into();
    }
    write_config(&path, &cfg)?;
    Ok(Some(path))
}

pub fn write_config(path: &Path, cfg: &BunnyConfig) -> Result<()> {
    let yaml = serde_yaml::to_string(cfg).context("serialize config")?;
    std::fs::write(path, yaml)?;
    Ok(())
}

/// Set the agent's public base URL in config.yaml.
pub fn set_server_public_url(public_url: &str) -> Result<PathBuf> {
    let path = config_path();
    let _ = ensure_user_config()?;
    let paths = vec![path.to_str().unwrap(), ".bunny.yaml"];
    let mut cfg = BunnyConfig::load(&paths)?;
    cfg.server.public_url = Some(public_url.to_string());
    write_config(&path, &cfg)?;
    Ok(path)
}

pub fn load_effective_config() -> Result<BunnyConfig> {
    let path = config_path();
    let paths = vec![path.to_str().unwrap(), ".bunny.yaml"];
    BunnyConfig::load(&paths)
}

pub fn apply_discord_to_config(bridge_token_hash: &str) -> Result<PathBuf> {
    let path = config_path();
    let _ = ensure_user_config()?;
    let paths = vec![path.to_str().unwrap(), ".bunny.yaml"];
    let mut cfg = BunnyConfig::load(&paths)?;
    cfg.discord.enabled = true;
    cfg.discord.bridge_token_hash = Some(bridge_token_hash.to_string());
    if Path::new("/.dockerenv").exists() {
        cfg.server.bind_host = "0.0.0.0".into();
    }
    write_config(&path, &cfg)?;
    Ok(path)
}

/// Store Discord OAuth client credentials in config.yaml (for user account linking from the Web UI).
pub fn apply_oauth_to_config(
    oauth_client_id: &str,
    oauth_client_secret: &str,
    oauth_redirect_uri: &str,
) -> Result<PathBuf> {
    let path = config_path();
    let _ = ensure_user_config()?;
    let paths = vec![path.to_str().unwrap(), ".bunny.yaml"];
    let mut cfg = BunnyConfig::load(&paths)?;
    cfg.discord.oauth_client_id = Some(oauth_client_id.to_string());
    cfg.discord.oauth_client_secret = Some(oauth_client_secret.to_string());
    cfg.discord.oauth_redirect_uri = Some(oauth_redirect_uri.to_string());
    write_config(&path, &cfg)?;
    Ok(path)
}

/// Read Discord Application ID from an existing bridge YAML (for OAuth setup hints).
pub fn read_bridge_application_id(path: &Path) -> Option<u64> {
    let text = std::fs::read_to_string(path).ok()?;
    let parsed: BridgeDevFile = serde_yaml::from_str(&text).ok()?;
    parsed.discord?.application_id
}

/// Read optional guild ID from an existing bridge YAML.
pub fn read_bridge_guild_id(path: &Path) -> Option<u64> {
    let text = std::fs::read_to_string(path).ok()?;
    let parsed: BridgeDevFile = serde_yaml::from_str(&text).ok()?;
    parsed.discord?.guild_id
}

pub fn write_bridge_dev_file(
    path: &Path,
    application_id: u64,
    bot_token: &str,
    bridge_token: &str,
    internal_url: &str,
    guild_id: Option<u64>,
) -> Result<()> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    let guild_id = guild_id.or_else(|| {
        path.is_file()
            .then(|| std::fs::read_to_string(path).ok())
            .flatten()
            .and_then(|text| serde_yaml::from_str::<BridgeDevFile>(&text).ok())
            .and_then(|f| f.discord.and_then(|d| d.guild_id))
    });
    let guild_line = guild_id
        .map(|id| format!("  guild_id: {id}\n"))
        .unwrap_or_default();
    let yaml = format!(
        r#"# Auto-generated by `bunny discord setup` — used by scripts/run-discord-bridge.sh on the host
discord:
  application_id: {application_id}
  bot_token: "{bot_token}"
{guild_line}bunny:
  internal_url: "{internal_url}"
  bridge_token: "{bridge_token}"
"#
    );
    std::fs::write(path, yaml)?;
    Ok(())
}

/// Copy `bunny.bridge_token` from bridge YAML into agent `config.yaml` (hashed).
/// Returns true when config was updated.
pub fn sync_agent_from_bridge_file(bridge_path: &Path) -> Result<bool> {
    if !bridge_path.is_file() {
        return Ok(false);
    }
    let text = std::fs::read_to_string(bridge_path)
        .with_context(|| format!("read {}", bridge_path.display()))?;
    let parsed: BridgeDevFile =
        serde_yaml::from_str(&text).context("parse bridge YAML (bunny.bridge_token)")?;
    let token = parsed.bunny.bridge_token.trim();
    if token.is_empty() {
        bail!("{}: bunny.bridge_token is empty", bridge_path.display());
    }
    let hash = hash_token(token);
    let path = config_path();
    let paths = vec![path.to_str().unwrap(), ".bunny.yaml"];
    let cfg = BunnyConfig::load(&paths)?;
    if cfg.discord.enabled && cfg.discord.bridge_token_hash.as_deref() == Some(hash.as_str()) {
        return Ok(false);
    }
    apply_discord_to_config(&hash)?;
    Ok(true)
}

pub fn generate_bridge_credentials() -> (String, String) {
    let plain: String = (0..32)
        .map(|_| {
            const CHARSET: &[u8] = b"abcdefghijklmnopqrstuvwxyz0123456789";
            let idx = rand::random::<usize>() % CHARSET.len();
            CHARSET[idx] as char
        })
        .collect();
    (plain.clone(), hash_token(&plain))
}
