import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Getting started',
      collapsed: false,
      items: [
        'getting-started/choose-your-path',
        'getting-started/install-docker',
        'getting-started/install-linux',
        'getting-started/install-dev',
        'getting-started/configure-server',
        'getting-started/first-run',
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      items: [{type: 'autogenerated', dirName: 'architecture'}],
    },
    {
      type: 'category',
      label: 'Team chats',
      items: [
        {
          type: 'category',
          label: 'Discord',
          items: [
            'team-chats/discord/setup',
            'team-chats/discord/workflows',
            'team-chats/discord/commands',
            'team-chats/discord/docker-mac',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Security',
      items: ['security/index'],
    },
    {
      type: 'category',
      label: 'Reference',
      items: ['reference/cli', 'api/index'],
    },
    {
      type: 'category',
      label: 'Mobile',
      items: [{type: 'autogenerated', dirName: 'mobile'}],
    },
    {
      type: 'category',
      label: 'Other',
      items: ['i18n', {type: 'autogenerated', dirName: 'improvements'}],
    },
  ],
};

export default sidebars;
